version: 2

models:
  - name: total_country_cases
    description: Cases and deaths per country
    columns:
      - name: country_region
        description: Name of country
      - name: cases
        description: Total number of COVID19 cases in country throughout history.
      - name: deaths
        description: Total number of COVID19 related deaths in country throughout history.

  - name: country_case_statistics
    description: COVID19 statistics per country
    columns:
      - name: country_region
        description: Name of country
#        data_tests:
#          - relationships:  # if foreign key relationship must be true. Not in this case.
#              arguments:
#                to: ref('countries')
#                field: country_region
      - name: cases
        description: Total number of COVID19 cases in country throughout history.
      - name: deaths
        description: Total number of COVID19 related deaths in country throughout history.
      - name: fatality_rate
        description: Percentage of cases leading to death.
      - name: cases_per_capita
        description: Percentage of population that was infected with COVID19.
