version: 2

models:
  - name: customers
    description: Summary of orders per customer
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.

  - name: stg_customers
    description: This model cleans up customer data. One record is a customer.
    columns:
      - name: customer_id
        description: Primary key
        data_tests:
          - unique
          - not_null

  - name: stg_orders
    description: This model cleans up order data. One record is an order by a customer.
    columns:
      - name: order_id
        description: Primary key
        data_tests:
          - unique
          - not_null
      - name: status
        description: Order status
        data_tests:
          - accepted_values:
              arguments:
                values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        description: Primary key
        data_tests:
          - not_null
          - relationships:  # validate foreign key
              arguments:
                to: ref('stg_customers')
                field: customer_id