version: 2

models:

  - name: countries
    description: Country demographics.
    columns:
      - name: country_code
        description: ISO3166_1 codename for country
        data_tests:
          - unique
          - not_null

      - name: country_region
        description: Name of country
        data_tests:
          - unique
          - not_null

      - name: total_population
        description: Total population of country.


  - name: cases
    description: Number of cases and deaths per day per country.
    columns:
      - name: country_code
        description: ISO3166_1 codename for country
        data_tests:
          - not_null

      - name: country_region
        description: Name of country
        data_tests:
          - not_null
  
      - name: cases
        description: Total number of COVID19 cases in country throughout history.

      - name: deaths
        description: Total number of COVID19 related deaths in country throughout history.

