sources:
    - name: source_covid19
      description: COVID-19 Epidemiological Data from Snowflake Marketplace
      database: SOURCE_COVID19_DATA
      schema: PUBLIC
      tables:
          - name: ecdc_global
            description: Daily cases per country.
          - name: databank_demographics
            description: Demographics per country area.